from __future__ import annotations

from harnesses.structured_patch.correction_templates import (
    CORRECTION_TEMPLATES,
    DEFAULT_CORRECTION_TEMPLATE_ID,
    SINGLE_CONSERVATIVE_CORRECTION_MESSAGE,
    SINGLE_CONSERVATIVE_CORRECTION_TEMPLATE_ID,
)

__all__ = [
    "CORRECTION_TEMPLATES",
    "DEFAULT_CORRECTION_TEMPLATE_ID",
    "SINGLE_CONSERVATIVE_CORRECTION_MESSAGE",
    "SINGLE_CONSERVATIVE_CORRECTION_TEMPLATE_ID",
]
